#!/bin/sh /etc/rc.common

START=99
STOP=99
USE_PROCD=1

PROG=/usr/bin/tuya_espd
CONF=tuya_espd

start_service() {
	local enabled device_id device_secret product_id
	
	config_load "$CONF"
	config_get enabled main enabled "0"
	config_get device_id main device_id
	config_get device_secret main device_secret
	config_get product_id main product_id

	if [ "$enabled" != "1" ]; then
		return 0
	fi

	if [ -z "$device_id" ] || [ -z "$device_secret" ] || [ -z "$product_id" ]; then
		logger -t tuya-espd "Cannot start: missing credentials in /etc/config/tuya_espd"
		return 1
	fi

	procd_open_instance
	procd_set_param command "$PROG" \
		-d "$device_id" \
		-s "$device_secret" \
		-p "$product_id"
	procd_set_param respawn 3600 5 5
	procd_set_param stderr 1
	procd_set_param file /etc/config/$CONF
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger "$CONF"
}

reload_service() {
	stop
	start
}
